sudo: false

language: java

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2
before_cache:
  - rm -rf $HOME/.m2/repository/org/concrete5
  - rm -rf $HOME/.m2/repository/.cache/tycho/p2-repository-metadata

env:
  global:
    - secure: "MykJYxGIi7TCk7naZEVMNmICU0DXeA5cJtGvIynGwzho8Bn/spc+iWs4WY/WfHEH/SQf0E0EuUzyGTZ3GUUpk4mUCUoUryZk7E43lyFKO5qlwTFicGR/G0VCdaH+jldFiBnAZmRidyD157iNea59yqpOECcWz38k83IqbIgL5Ag8aPLPcnyHuWxJ1YSA77FZPrfSnKMbLqvzhpBAx0JK1o47mFaGVoW0ib3IxSPOjib6Hyvodjj5zU/BBSlNpEObr4cxxlw9VU1SsO9zP1x4e81mkRfLNahRVI4/USMEAMgrCPXANd9JWmwh6kkQLV8tqZ/86rmrbVhJl2IV4kGCqSGPiiMnoWw8sfnzNwxYKdiSBRf0kpXEHYXYMcRSEMlcGbGBNOlx3zlkqjYf4yq8fKUU8o/B87qgakxwHlIbzfxCk6k9HfW2wJuuI8ptoXdoqsM1es+cvLEvvJyz8zMWmKw/8goyRldh+SamsTksnQaQ6CcI6beLPiHzeSrtd01R+JfqvL55jzzY+ROtX6fwS1rJVJalecM0gco6XsLXLk400DS0k85cU91YQRgkouZIZEqU5jVwzEFqE80cl/ScSPoTxPqaZcwTQSBb5FL7F6x688i/Qdzi/lfXUgVCP+Hp2mWr8VE8otwPIDatFFpBC0+w0UlNbJJfulwZykPzCco="

install:
  - true

script:
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode --show-version
  - ./.travis-deploy.sh

notifications:
  email: false
